// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: rank.sql

package db

import (
	"context"
)

const getRank = `-- name: GetRank :one
SELECT name, score
FROM rank
WHERE score <= $1
ORDER BY score DESC
LIMIT 1
`

type GetRankRow struct {
	Name  string `json:"name"`
	Score int32  `json:"score"`
}

func (q *Queries) GetRank(ctx context.Context, score int32) (GetRankRow, error) {
	row := q.db.QueryRowContext(ctx, getRank, score)
	var i GetRankRow
	err := row.Scan(&i.Name, &i.Score)
	return i, err
}
