// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: rcm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookRecommendClient is the client API for BookRecommend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookRecommendClient interface {
	GetBookRecommend(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookResponse, error)
}

type bookRecommendClient struct {
	cc grpc.ClientConnInterface
}

func NewBookRecommendClient(cc grpc.ClientConnInterface) BookRecommendClient {
	return &bookRecommendClient{cc}
}

func (c *bookRecommendClient) GetBookRecommend(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookResponse, error) {
	out := new(BookResponse)
	err := c.cc.Invoke(ctx, "/pb.BookRecommend/GetBookRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookRecommendServer is the server API for BookRecommend service.
// All implementations must embed UnimplementedBookRecommendServer
// for forward compatibility
type BookRecommendServer interface {
	GetBookRecommend(context.Context, *BookRequest) (*BookResponse, error)
	mustEmbedUnimplementedBookRecommendServer()
}

// UnimplementedBookRecommendServer must be embedded to have forward compatible implementations.
type UnimplementedBookRecommendServer struct {
}

func (UnimplementedBookRecommendServer) GetBookRecommend(context.Context, *BookRequest) (*BookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookRecommend not implemented")
}
func (UnimplementedBookRecommendServer) mustEmbedUnimplementedBookRecommendServer() {}

// UnsafeBookRecommendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookRecommendServer will
// result in compilation errors.
type UnsafeBookRecommendServer interface {
	mustEmbedUnimplementedBookRecommendServer()
}

func RegisterBookRecommendServer(s grpc.ServiceRegistrar, srv BookRecommendServer) {
	s.RegisterService(&BookRecommend_ServiceDesc, srv)
}

func _BookRecommend_GetBookRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookRecommendServer).GetBookRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BookRecommend/GetBookRecommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookRecommendServer).GetBookRecommend(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookRecommend_ServiceDesc is the grpc.ServiceDesc for BookRecommend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookRecommend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BookRecommend",
	HandlerType: (*BookRecommendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookRecommend",
			Handler:    _BookRecommend_GetBookRecommend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rcm.proto",
}
