// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: address.sql

package db

import (
	"context"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
  users_id,
  address,
  district,
  city
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, address, users_id, district, city, created_at
`

type CreateAddressParams struct {
	UsersID  int64  `json:"users_id"`
	Address  string `json:"address"`
	District string `json:"district"`
	City     string `json:"city"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, createAddress,
		arg.UsersID,
		arg.Address,
		arg.District,
		arg.City,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.UsersID,
		&i.District,
		&i.City,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM address
WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAddress, id)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT id, address, users_id, district, city, created_at FROM address
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAddress(ctx context.Context, id int64) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddress, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.UsersID,
		&i.District,
		&i.City,
		&i.CreatedAt,
	)
	return i, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, address, users_id, district, city, created_at FROM address
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAddressesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAddresses(ctx context.Context, arg ListAddressesParams) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, listAddresses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.UsersID,
			&i.District,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE address
SET  address = $2,
  district = $3,
  city = $4
WHERE id = $1
RETURNING id, address, users_id, district, city, created_at
`

type UpdateAddressParams struct {
	ID       int64  `json:"id"`
	Address  string `json:"address"`
	District string `json:"district"`
	City     string `json:"city"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, updateAddress,
		arg.ID,
		arg.Address,
		arg.District,
		arg.City,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.UsersID,
		&i.District,
		&i.City,
		&i.CreatedAt,
	)
	return i, err
}
