// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: carts.sql

package db

import (
	"context"
)

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
    users_id
) VALUES (
  $1
)
RETURNING id, users_id, created_at
`

func (q *Queries) CreateCart(ctx context.Context, usersID int64) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, usersID)
	var i Cart
	err := row.Scan(&i.ID, &i.UsersID, &i.CreatedAt)
	return i, err
}

const getCart = `-- name: GetCart :one
SELECT id, users_id, created_at FROM carts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCart(ctx context.Context, id int64) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCart, id)
	var i Cart
	err := row.Scan(&i.ID, &i.UsersID, &i.CreatedAt)
	return i, err
}
