// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: shippings.sql

package db

import (
	"context"
)

const createShipping = `-- name: CreateShipping :one
INSERT INTO shippings (
  from_address,
  to_address,
  total
) VALUES (
  $1, $2, $3
)
RETURNING id, from_address, to_address, total
`

type CreateShippingParams struct {
	FromAddress string  `json:"from_address"`
	ToAddress   string  `json:"to_address"`
	Total       float64 `json:"total"`
}

func (q *Queries) CreateShipping(ctx context.Context, arg CreateShippingParams) (Shipping, error) {
	row := q.db.QueryRowContext(ctx, createShipping, arg.FromAddress, arg.ToAddress, arg.Total)
	var i Shipping
	err := row.Scan(
		&i.ID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Total,
	)
	return i, err
}
