Project nmc_bookstore {
  database_type: 'PostgreSQL'
  Note: '''
    # NMC Bookstore Database
  '''
}


Table users as U {
  username varchar [not null, pk]
  full_name varchar [not null]
  email varchar [not null, unique]
  password varchar [not null]
  image varchar [not null]
  phone_number varchar [not null]
  role varchar [not null]
  password_changed_at timestamptz [not null, default: '0001-01-01 00:00:00Z']
  is_email_verified boolean [not null, default: false]
  created_at timestamptz [not null, default:"now()"]
}

Table verify_emails {
  id bigserial [pk]
  username varchar [ref: > U.username, not null]
  email varchar [not null]
  secret_code varchar [not null]
  is_used bool [not null, default: false]
  created_at timestamptz [not null, default:'now()']
  expired_at timestamptz [not null, default:`now()  + interval '15 minutes'`]
}

Table reset_passwords {
  id bigserial [pk]
  username varchar [ref: > U.username, not null]
  reset_code varchar [not null]
  is_used bool [not null, default: false]
  created_at timestamptz [not null, default:'now()']
  expired_at timestamptz [not null, default:`now()  + interval '15 minutes'`]
}

Table address as A{
  id bigserial [pk, increment]
  address varchar [not null]
  username varchar [ref: > U.username, not null]
  district varchar [not null]
  city varchar [not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes{
    username
  }
}

Table books as B {
  id bigserial [pk, increment]
  name varchar [not null]
  price float [not null]
  image varchar[] [not null]
  description varchar [not null]
  author varchar [not null]
  publisher varchar [not null]
  quantity int [not null]
  created_at timestamptz [not null, default:"now()"]
}

Table genres as G{
  id bigserial [pk, increment]
  name varchar [not null]
  created_at timestamptz [not null, default:"now()"]
}

Table subgenres as SG{
  id bigserial [pk, increment]
  genres_id bigserial [ref: > G.id, not null]
  name varchar [not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes {
     genres_id
  }
}

Table carts as BC{
  id bigserial [pk, increment]
  books_id bigserial [ref: > B.id, not null]
  username varchar [ref: > U.username, not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes{
    books_id
    username
    (books_id, username)
  }
}

Table books_genres as BG {
  id bigserial [pk, increment]
  books_id bigserial [ref: > B.id, not null]
  genres_id bigserial [ref: > G.id, not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes {
    books_id
    genres_id
    (books_id, genres_id)
  }
}

Table books_subgenres as BS {
  id bigserial [pk, increment]
  books_id bigserial [ref: > B.id, not null]
  subgenres_id bigserial [ref: > SG.id, not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes {
    books_id
    subgenres_id
    (books_id, subgenres_id)
  }
}

Table reviews as R {
  id bigserial [pk, increment]
  username varchar [ref: > U.username, not null]
  books_id bigserial [ref: > B.id, not null]
  comments varchar [not null]
  rating int [not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes{
    username
    books_id
    (username, books_id)
  }
}

Table orders as O {
  id bigserial [pk, increment]
  username varchar [ref: > U.username, not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes{
    username
  }
}

Table transactions as T {
  id bigserial [pk, increment]
  orders_id bigserial [ref: > O.id, not null]
  books_id bigserial [ref: > B.id, not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes{
    books_id
    orders_id
    (books_id, orders_id)
  }
}

Table wishlists as BW{
  id bigserial [pk, increment]
  books_id bigserial [ref: > B.id, not null]
  username varchar [ref: > U.username, not null]
  created_at timestamptz [not null, default:"now()"]
  
  indexes{
    books_id
    username
    (books_id, username)
  }
}

Table sessions {
    id uuid [pk]
    username varchar [ref: > U.username, not null]
    refresh_token varchar [not null]
    user_agent varchar [not null]
    client_ip varchar [not null]
    is_blocked boolean [not null, default: 'false']
    expires_at timestamptz [not null]
    created_at timestamptz [not null, default:'now()']
}