// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Chien179/NMCBookstoreBE/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/Chien179/NMCBookstoreBE/db/sqlc"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAddress mocks base method.
func (m *MockStore) CreateAddress(arg0 context.Context, arg1 db.CreateAddressParams) (db.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAddress", arg0, arg1)
	ret0, _ := ret[0].(db.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAddress indicates an expected call of CreateAddress.
func (mr *MockStoreMockRecorder) CreateAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAddress", reflect.TypeOf((*MockStore)(nil).CreateAddress), arg0, arg1)
}

// CreateBook mocks base method.
func (m *MockStore) CreateBook(arg0 context.Context, arg1 db.CreateBookParams) (db.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBook", arg0, arg1)
	ret0, _ := ret[0].(db.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBook indicates an expected call of CreateBook.
func (mr *MockStoreMockRecorder) CreateBook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBook", reflect.TypeOf((*MockStore)(nil).CreateBook), arg0, arg1)
}

// CreateBookGenre mocks base method.
func (m *MockStore) CreateBookGenre(arg0 context.Context, arg1 db.CreateBookGenreParams) (db.BooksGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookGenre", arg0, arg1)
	ret0, _ := ret[0].(db.BooksGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookGenre indicates an expected call of CreateBookGenre.
func (mr *MockStoreMockRecorder) CreateBookGenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookGenre", reflect.TypeOf((*MockStore)(nil).CreateBookGenre), arg0, arg1)
}

// CreateBookSubgenre mocks base method.
func (m *MockStore) CreateBookSubgenre(arg0 context.Context, arg1 db.CreateBookSubgenreParams) (db.BooksSubgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookSubgenre", arg0, arg1)
	ret0, _ := ret[0].(db.BooksSubgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookSubgenre indicates an expected call of CreateBookSubgenre.
func (mr *MockStoreMockRecorder) CreateBookSubgenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookSubgenre", reflect.TypeOf((*MockStore)(nil).CreateBookSubgenre), arg0, arg1)
}

// CreateCart mocks base method.
func (m *MockStore) CreateCart(arg0 context.Context, arg1 db.CreateCartParams) (db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", arg0, arg1)
	ret0, _ := ret[0].(db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockStoreMockRecorder) CreateCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockStore)(nil).CreateCart), arg0, arg1)
}

// CreateGenre mocks base method.
func (m *MockStore) CreateGenre(arg0 context.Context, arg1 string) (db.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGenre", arg0, arg1)
	ret0, _ := ret[0].(db.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGenre indicates an expected call of CreateGenre.
func (mr *MockStoreMockRecorder) CreateGenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGenre", reflect.TypeOf((*MockStore)(nil).CreateGenre), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockStore) CreateOrder(arg0 context.Context, arg1 string) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStoreMockRecorder) CreateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStore)(nil).CreateOrder), arg0, arg1)
}

// CreatePayment mocks base method.
func (m *MockStore) CreatePayment(arg0 context.Context, arg1 db.CreatePaymentParams) (db.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", arg0, arg1)
	ret0, _ := ret[0].(db.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockStoreMockRecorder) CreatePayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockStore)(nil).CreatePayment), arg0, arg1)
}

// CreateResetPassword mocks base method.
func (m *MockStore) CreateResetPassword(arg0 context.Context, arg1 db.CreateResetPasswordParams) (db.ResetPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResetPassword", arg0, arg1)
	ret0, _ := ret[0].(db.ResetPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResetPassword indicates an expected call of CreateResetPassword.
func (mr *MockStoreMockRecorder) CreateResetPassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResetPassword", reflect.TypeOf((*MockStore)(nil).CreateResetPassword), arg0, arg1)
}

// CreateReview mocks base method.
func (m *MockStore) CreateReview(arg0 context.Context, arg1 db.CreateReviewParams) (db.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", arg0, arg1)
	ret0, _ := ret[0].(db.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockStoreMockRecorder) CreateReview(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockStore)(nil).CreateReview), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(arg0 context.Context, arg1 db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), arg0, arg1)
}

// CreateShipping mocks base method.
func (m *MockStore) CreateShipping(arg0 context.Context, arg1 db.CreateShippingParams) (db.Shipping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShipping", arg0, arg1)
	ret0, _ := ret[0].(db.Shipping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShipping indicates an expected call of CreateShipping.
func (mr *MockStoreMockRecorder) CreateShipping(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShipping", reflect.TypeOf((*MockStore)(nil).CreateShipping), arg0, arg1)
}

// CreateSubgenre mocks base method.
func (m *MockStore) CreateSubgenre(arg0 context.Context, arg1 db.CreateSubgenreParams) (db.Subgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubgenre", arg0, arg1)
	ret0, _ := ret[0].(db.Subgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubgenre indicates an expected call of CreateSubgenre.
func (mr *MockStoreMockRecorder) CreateSubgenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubgenre", reflect.TypeOf((*MockStore)(nil).CreateSubgenre), arg0, arg1)
}

// CreateTransaction mocks base method.
func (m *MockStore) CreateTransaction(arg0 context.Context, arg1 db.CreateTransactionParams) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockStoreMockRecorder) CreateTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockStore)(nil).CreateTransaction), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserTx mocks base method.
func (m *MockStore) CreateUserTx(arg0 context.Context, arg1 db.CreateUserTxParams) (db.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockStoreMockRecorder) CreateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockStore)(nil).CreateUserTx), arg0, arg1)
}

// CreateVerifyEmail mocks base method.
func (m *MockStore) CreateVerifyEmail(arg0 context.Context, arg1 db.CreateVerifyEmailParams) (db.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerifyEmail indicates an expected call of CreateVerifyEmail.
func (mr *MockStoreMockRecorder) CreateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyEmail", reflect.TypeOf((*MockStore)(nil).CreateVerifyEmail), arg0, arg1)
}

// CreateWishlist mocks base method.
func (m *MockStore) CreateWishlist(arg0 context.Context, arg1 db.CreateWishlistParams) (db.Wishlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWishlist", arg0, arg1)
	ret0, _ := ret[0].(db.Wishlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWishlist indicates an expected call of CreateWishlist.
func (mr *MockStoreMockRecorder) CreateWishlist(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWishlist", reflect.TypeOf((*MockStore)(nil).CreateWishlist), arg0, arg1)
}

// DeleteAddress mocks base method.
func (m *MockStore) DeleteAddress(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockStoreMockRecorder) DeleteAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockStore)(nil).DeleteAddress), arg0, arg1)
}

// DeleteBook mocks base method.
func (m *MockStore) DeleteBook(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBook", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBook indicates an expected call of DeleteBook.
func (mr *MockStoreMockRecorder) DeleteBook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBook", reflect.TypeOf((*MockStore)(nil).DeleteBook), arg0, arg1)
}

// DeleteBookGenre mocks base method.
func (m *MockStore) DeleteBookGenre(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookGenre", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookGenre indicates an expected call of DeleteBookGenre.
func (mr *MockStoreMockRecorder) DeleteBookGenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookGenre", reflect.TypeOf((*MockStore)(nil).DeleteBookGenre), arg0, arg1)
}

// DeleteBookSubgenre mocks base method.
func (m *MockStore) DeleteBookSubgenre(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookSubgenre", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookSubgenre indicates an expected call of DeleteBookSubgenre.
func (mr *MockStoreMockRecorder) DeleteBookSubgenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookSubgenre", reflect.TypeOf((*MockStore)(nil).DeleteBookSubgenre), arg0, arg1)
}

// DeleteCart mocks base method.
func (m *MockStore) DeleteCart(arg0 context.Context, arg1 db.DeleteCartParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCart", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCart indicates an expected call of DeleteCart.
func (mr *MockStoreMockRecorder) DeleteCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCart", reflect.TypeOf((*MockStore)(nil).DeleteCart), arg0, arg1)
}

// DeleteGenre mocks base method.
func (m *MockStore) DeleteGenre(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGenre", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGenre indicates an expected call of DeleteGenre.
func (mr *MockStoreMockRecorder) DeleteGenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGenre", reflect.TypeOf((*MockStore)(nil).DeleteGenre), arg0, arg1)
}

// DeleteOrder mocks base method.
func (m *MockStore) DeleteOrder(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockStoreMockRecorder) DeleteOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockStore)(nil).DeleteOrder), arg0, arg1)
}

// DeleteReview mocks base method.
func (m *MockStore) DeleteReview(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReview", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockStoreMockRecorder) DeleteReview(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockStore)(nil).DeleteReview), arg0, arg1)
}

// DeleteSubgenre mocks base method.
func (m *MockStore) DeleteSubgenre(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubgenre", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubgenre indicates an expected call of DeleteSubgenre.
func (mr *MockStoreMockRecorder) DeleteSubgenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubgenre", reflect.TypeOf((*MockStore)(nil).DeleteSubgenre), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// DeleteWishlist mocks base method.
func (m *MockStore) DeleteWishlist(arg0 context.Context, arg1 db.DeleteWishlistParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWishlist", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWishlist indicates an expected call of DeleteWishlist.
func (mr *MockStoreMockRecorder) DeleteWishlist(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWishlist", reflect.TypeOf((*MockStore)(nil).DeleteWishlist), arg0, arg1)
}

// FullSearch mocks base method.
func (m *MockStore) FullSearch(arg0 context.Context, arg1 db.FullSearchParams) (db.FullSearchRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullSearch", arg0, arg1)
	ret0, _ := ret[0].(db.FullSearchRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FullSearch indicates an expected call of FullSearch.
func (mr *MockStoreMockRecorder) FullSearch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullSearch", reflect.TypeOf((*MockStore)(nil).FullSearch), arg0, arg1)
}

// GetAddress mocks base method.
func (m *MockStore) GetAddress(arg0 context.Context, arg1 int64) (db.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddress", arg0, arg1)
	ret0, _ := ret[0].(db.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddress indicates an expected call of GetAddress.
func (mr *MockStoreMockRecorder) GetAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddress", reflect.TypeOf((*MockStore)(nil).GetAddress), arg0, arg1)
}

// GetBook mocks base method.
func (m *MockStore) GetBook(arg0 context.Context, arg1 int64) (db.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBook", arg0, arg1)
	ret0, _ := ret[0].(db.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBook indicates an expected call of GetBook.
func (mr *MockStoreMockRecorder) GetBook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBook", reflect.TypeOf((*MockStore)(nil).GetBook), arg0, arg1)
}

// GetBookGenre mocks base method.
func (m *MockStore) GetBookGenre(arg0 context.Context, arg1 int64) (db.BooksGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookGenre", arg0, arg1)
	ret0, _ := ret[0].(db.BooksGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookGenre indicates an expected call of GetBookGenre.
func (mr *MockStoreMockRecorder) GetBookGenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookGenre", reflect.TypeOf((*MockStore)(nil).GetBookGenre), arg0, arg1)
}

// GetBookSubgenre mocks base method.
func (m *MockStore) GetBookSubgenre(arg0 context.Context, arg1 int64) (db.BooksSubgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookSubgenre", arg0, arg1)
	ret0, _ := ret[0].(db.BooksSubgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookSubgenre indicates an expected call of GetBookSubgenre.
func (mr *MockStoreMockRecorder) GetBookSubgenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookSubgenre", reflect.TypeOf((*MockStore)(nil).GetBookSubgenre), arg0, arg1)
}

// GetCart mocks base method.
func (m *MockStore) GetCart(arg0 context.Context, arg1 int64) (db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", arg0, arg1)
	ret0, _ := ret[0].(db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockStoreMockRecorder) GetCart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockStore)(nil).GetCart), arg0, arg1)
}

// GetCity mocks base method.
func (m *MockStore) GetCity(arg0 context.Context, arg1 int64) (db.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCity", arg0, arg1)
	ret0, _ := ret[0].(db.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCity indicates an expected call of GetCity.
func (mr *MockStoreMockRecorder) GetCity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCity", reflect.TypeOf((*MockStore)(nil).GetCity), arg0, arg1)
}

// GetDistrict mocks base method.
func (m *MockStore) GetDistrict(arg0 context.Context, arg1 int64) (db.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistrict", arg0, arg1)
	ret0, _ := ret[0].(db.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistrict indicates an expected call of GetDistrict.
func (mr *MockStoreMockRecorder) GetDistrict(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistrict", reflect.TypeOf((*MockStore)(nil).GetDistrict), arg0, arg1)
}

// GetGenre mocks base method.
func (m *MockStore) GetGenre(arg0 context.Context, arg1 int64) (db.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenre", arg0, arg1)
	ret0, _ := ret[0].(db.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenre indicates an expected call of GetGenre.
func (mr *MockStoreMockRecorder) GetGenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenre", reflect.TypeOf((*MockStore)(nil).GetGenre), arg0, arg1)
}

// GetOrder mocks base method.
func (m *MockStore) GetOrder(arg0 context.Context, arg1 int64) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockStoreMockRecorder) GetOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockStore)(nil).GetOrder), arg0, arg1)
}

// GetOrderToPayment mocks base method.
func (m *MockStore) GetOrderToPayment(arg0 context.Context, arg1 string) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderToPayment", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderToPayment indicates an expected call of GetOrderToPayment.
func (mr *MockStoreMockRecorder) GetOrderToPayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderToPayment", reflect.TypeOf((*MockStore)(nil).GetOrderToPayment), arg0, arg1)
}

// GetReview mocks base method.
func (m *MockStore) GetReview(arg0 context.Context, arg1 int64) (db.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReview", arg0, arg1)
	ret0, _ := ret[0].(db.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReview indicates an expected call of GetReview.
func (mr *MockStoreMockRecorder) GetReview(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReview", reflect.TypeOf((*MockStore)(nil).GetReview), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(arg0 context.Context, arg1 uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), arg0, arg1)
}

// GetSubgenre mocks base method.
func (m *MockStore) GetSubgenre(arg0 context.Context, arg1 int64) (db.Subgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubgenre", arg0, arg1)
	ret0, _ := ret[0].(db.Subgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubgenre indicates an expected call of GetSubgenre.
func (mr *MockStoreMockRecorder) GetSubgenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubgenre", reflect.TypeOf((*MockStore)(nil).GetSubgenre), arg0, arg1)
}

// GetTransaction mocks base method.
func (m *MockStore) GetTransaction(arg0 context.Context, arg1 int64) (db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockStoreMockRecorder) GetTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockStore)(nil).GetTransaction), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetWishlist mocks base method.
func (m *MockStore) GetWishlist(arg0 context.Context, arg1 int64) (db.Wishlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWishlist", arg0, arg1)
	ret0, _ := ret[0].(db.Wishlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWishlist indicates an expected call of GetWishlist.
func (mr *MockStoreMockRecorder) GetWishlist(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWishlist", reflect.TypeOf((*MockStore)(nil).GetWishlist), arg0, arg1)
}

// ListAddresses mocks base method.
func (m *MockStore) ListAddresses(arg0 context.Context, arg1 string) ([]db.ListAddressesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddresses", arg0, arg1)
	ret0, _ := ret[0].([]db.ListAddressesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddresses indicates an expected call of ListAddresses.
func (mr *MockStoreMockRecorder) ListAddresses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddresses", reflect.TypeOf((*MockStore)(nil).ListAddresses), arg0, arg1)
}

// ListAllBooks mocks base method.
func (m *MockStore) ListAllBooks(arg0 context.Context) ([]db.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllBooks", arg0)
	ret0, _ := ret[0].([]db.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllBooks indicates an expected call of ListAllBooks.
func (mr *MockStoreMockRecorder) ListAllBooks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllBooks", reflect.TypeOf((*MockStore)(nil).ListAllBooks), arg0)
}

// ListBooks mocks base method.
func (m *MockStore) ListBooks(arg0 context.Context, arg1 db.ListBooksParams) (db.ListBooksRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks", arg0, arg1)
	ret0, _ := ret[0].(db.ListBooksRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockStoreMockRecorder) ListBooks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockStore)(nil).ListBooks), arg0, arg1)
}

// ListBooksGenresByBookID mocks base method.
func (m *MockStore) ListBooksGenresByBookID(arg0 context.Context, arg1 int64) ([]db.BooksGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooksGenresByBookID", arg0, arg1)
	ret0, _ := ret[0].([]db.BooksGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooksGenresByBookID indicates an expected call of ListBooksGenresByBookID.
func (mr *MockStoreMockRecorder) ListBooksGenresByBookID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooksGenresByBookID", reflect.TypeOf((*MockStore)(nil).ListBooksGenresByBookID), arg0, arg1)
}

// ListBooksGenresByGenreID mocks base method.
func (m *MockStore) ListBooksGenresByGenreID(arg0 context.Context, arg1 int64) ([]db.BooksGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooksGenresByGenreID", arg0, arg1)
	ret0, _ := ret[0].([]db.BooksGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooksGenresByGenreID indicates an expected call of ListBooksGenresByGenreID.
func (mr *MockStoreMockRecorder) ListBooksGenresByGenreID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooksGenresByGenreID", reflect.TypeOf((*MockStore)(nil).ListBooksGenresByGenreID), arg0, arg1)
}

// ListBooksSubgenresByBookID mocks base method.
func (m *MockStore) ListBooksSubgenresByBookID(arg0 context.Context, arg1 int64) ([]db.BooksSubgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooksSubgenresByBookID", arg0, arg1)
	ret0, _ := ret[0].([]db.BooksSubgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooksSubgenresByBookID indicates an expected call of ListBooksSubgenresByBookID.
func (mr *MockStoreMockRecorder) ListBooksSubgenresByBookID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooksSubgenresByBookID", reflect.TypeOf((*MockStore)(nil).ListBooksSubgenresByBookID), arg0, arg1)
}

// ListBooksSubgenresBySubgenreID mocks base method.
func (m *MockStore) ListBooksSubgenresBySubgenreID(arg0 context.Context, arg1 int64) ([]db.BooksSubgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooksSubgenresBySubgenreID", arg0, arg1)
	ret0, _ := ret[0].([]db.BooksSubgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooksSubgenresBySubgenreID indicates an expected call of ListBooksSubgenresBySubgenreID.
func (mr *MockStoreMockRecorder) ListBooksSubgenresBySubgenreID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooksSubgenresBySubgenreID", reflect.TypeOf((*MockStore)(nil).ListBooksSubgenresBySubgenreID), arg0, arg1)
}

// ListCartsByUsername mocks base method.
func (m *MockStore) ListCartsByUsername(arg0 context.Context, arg1 string) ([]db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartsByUsername", arg0, arg1)
	ret0, _ := ret[0].([]db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartsByUsername indicates an expected call of ListCartsByUsername.
func (mr *MockStoreMockRecorder) ListCartsByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartsByUsername", reflect.TypeOf((*MockStore)(nil).ListCartsByUsername), arg0, arg1)
}

// ListCities mocks base method.
func (m *MockStore) ListCities(arg0 context.Context) ([]db.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCities", arg0)
	ret0, _ := ret[0].([]db.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCities indicates an expected call of ListCities.
func (mr *MockStoreMockRecorder) ListCities(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCities", reflect.TypeOf((*MockStore)(nil).ListCities), arg0)
}

// ListDistricts mocks base method.
func (m *MockStore) ListDistricts(arg0 context.Context, arg1 int64) ([]db.District, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDistricts", arg0, arg1)
	ret0, _ := ret[0].([]db.District)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistricts indicates an expected call of ListDistricts.
func (mr *MockStoreMockRecorder) ListDistricts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistricts", reflect.TypeOf((*MockStore)(nil).ListDistricts), arg0, arg1)
}

// ListGenres mocks base method.
func (m *MockStore) ListGenres(arg0 context.Context) ([]db.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGenres", arg0)
	ret0, _ := ret[0].([]db.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGenres indicates an expected call of ListGenres.
func (mr *MockStoreMockRecorder) ListGenres(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGenres", reflect.TypeOf((*MockStore)(nil).ListGenres), arg0)
}

// ListNewestBooks mocks base method.
func (m *MockStore) ListNewestBooks(arg0 context.Context) ([]db.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNewestBooks", arg0)
	ret0, _ := ret[0].([]db.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNewestBooks indicates an expected call of ListNewestBooks.
func (mr *MockStoreMockRecorder) ListNewestBooks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNewestBooks", reflect.TypeOf((*MockStore)(nil).ListNewestBooks), arg0)
}

// ListOders mocks base method.
func (m *MockStore) ListOders(arg0 context.Context) ([]db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOders", arg0)
	ret0, _ := ret[0].([]db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOders indicates an expected call of ListOders.
func (mr *MockStoreMockRecorder) ListOders(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOders", reflect.TypeOf((*MockStore)(nil).ListOders), arg0)
}

// ListOdersByUserName mocks base method.
func (m *MockStore) ListOdersByUserName(arg0 context.Context, arg1 string) ([]db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOdersByUserName", arg0, arg1)
	ret0, _ := ret[0].([]db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOdersByUserName indicates an expected call of ListOdersByUserName.
func (mr *MockStoreMockRecorder) ListOdersByUserName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOdersByUserName", reflect.TypeOf((*MockStore)(nil).ListOdersByUserName), arg0, arg1)
}

// ListReviewsByBookID mocks base method.
func (m *MockStore) ListReviewsByBookID(arg0 context.Context, arg1 db.ListReviewsByBookIDParams) (db.ListReviewsByBookIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviewsByBookID", arg0, arg1)
	ret0, _ := ret[0].(db.ListReviewsByBookIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviewsByBookID indicates an expected call of ListReviewsByBookID.
func (mr *MockStoreMockRecorder) ListReviewsByBookID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviewsByBookID", reflect.TypeOf((*MockStore)(nil).ListReviewsByBookID), arg0, arg1)
}

// ListSubgenres mocks base method.
func (m *MockStore) ListSubgenres(arg0 context.Context, arg1 int64) ([]db.Subgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubgenres", arg0, arg1)
	ret0, _ := ret[0].([]db.Subgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubgenres indicates an expected call of ListSubgenres.
func (mr *MockStoreMockRecorder) ListSubgenres(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubgenres", reflect.TypeOf((*MockStore)(nil).ListSubgenres), arg0, arg1)
}

// ListSubgenresNoticeable mocks base method.
func (m *MockStore) ListSubgenresNoticeable(arg0 context.Context) ([]db.ListSubgenresNoticeableRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubgenresNoticeable", arg0)
	ret0, _ := ret[0].([]db.ListSubgenresNoticeableRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubgenresNoticeable indicates an expected call of ListSubgenresNoticeable.
func (mr *MockStoreMockRecorder) ListSubgenresNoticeable(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubgenresNoticeable", reflect.TypeOf((*MockStore)(nil).ListSubgenresNoticeable), arg0)
}

// ListTheBestBooks mocks base method.
func (m *MockStore) ListTheBestBooks(arg0 context.Context) ([]db.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTheBestBooks", arg0)
	ret0, _ := ret[0].([]db.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTheBestBooks indicates an expected call of ListTheBestBooks.
func (mr *MockStoreMockRecorder) ListTheBestBooks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTheBestBooks", reflect.TypeOf((*MockStore)(nil).ListTheBestBooks), arg0)
}

// ListTransactionsByOrderID mocks base method.
func (m *MockStore) ListTransactionsByOrderID(arg0 context.Context, arg1 int64) ([]db.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByOrderID", arg0, arg1)
	ret0, _ := ret[0].([]db.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByOrderID indicates an expected call of ListTransactionsByOrderID.
func (mr *MockStoreMockRecorder) ListTransactionsByOrderID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByOrderID", reflect.TypeOf((*MockStore)(nil).ListTransactionsByOrderID), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(arg0 context.Context, arg1 db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), arg0, arg1)
}

// ListWishlistsByUsername mocks base method.
func (m *MockStore) ListWishlistsByUsername(arg0 context.Context, arg1 string) ([]db.Wishlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWishlistsByUsername", arg0, arg1)
	ret0, _ := ret[0].([]db.Wishlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWishlistsByUsername indicates an expected call of ListWishlistsByUsername.
func (mr *MockStoreMockRecorder) ListWishlistsByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWishlistsByUsername", reflect.TypeOf((*MockStore)(nil).ListWishlistsByUsername), arg0, arg1)
}

// ResetPasswordTx mocks base method.
func (m *MockStore) ResetPasswordTx(arg0 context.Context, arg1 db.ResetPasswordTxParams) (db.ResetPasswordTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordTx", arg0, arg1)
	ret0, _ := ret[0].(db.ResetPasswordTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetPasswordTx indicates an expected call of ResetPasswordTx.
func (mr *MockStoreMockRecorder) ResetPasswordTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordTx", reflect.TypeOf((*MockStore)(nil).ResetPasswordTx), arg0, arg1)
}

// RevenueDays mocks base method.
func (m *MockStore) RevenueDays(arg0 context.Context) ([]db.RevenueDaysRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevenueDays", arg0)
	ret0, _ := ret[0].([]db.RevenueDaysRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevenueDays indicates an expected call of RevenueDays.
func (mr *MockStoreMockRecorder) RevenueDays(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevenueDays", reflect.TypeOf((*MockStore)(nil).RevenueDays), arg0)
}

// RevenueMonths mocks base method.
func (m *MockStore) RevenueMonths(arg0 context.Context) ([]db.RevenueMonthsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevenueMonths", arg0)
	ret0, _ := ret[0].([]db.RevenueMonthsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevenueMonths indicates an expected call of RevenueMonths.
func (mr *MockStoreMockRecorder) RevenueMonths(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevenueMonths", reflect.TypeOf((*MockStore)(nil).RevenueMonths), arg0)
}

// RevenueQuarters mocks base method.
func (m *MockStore) RevenueQuarters(arg0 context.Context) ([]db.RevenueQuartersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevenueQuarters", arg0)
	ret0, _ := ret[0].([]db.RevenueQuartersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevenueQuarters indicates an expected call of RevenueQuarters.
func (mr *MockStoreMockRecorder) RevenueQuarters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevenueQuarters", reflect.TypeOf((*MockStore)(nil).RevenueQuarters), arg0)
}

// RevenueYears mocks base method.
func (m *MockStore) RevenueYears(arg0 context.Context) ([]db.RevenueYearsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevenueYears", arg0)
	ret0, _ := ret[0].([]db.RevenueYearsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevenueYears indicates an expected call of RevenueYears.
func (mr *MockStoreMockRecorder) RevenueYears(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevenueYears", reflect.TypeOf((*MockStore)(nil).RevenueYears), arg0)
}

// UpdateAddress mocks base method.
func (m *MockStore) UpdateAddress(arg0 context.Context, arg1 db.UpdateAddressParams) (db.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", arg0, arg1)
	ret0, _ := ret[0].(db.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockStoreMockRecorder) UpdateAddress(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockStore)(nil).UpdateAddress), arg0, arg1)
}

// UpdateAmount mocks base method.
func (m *MockStore) UpdateAmount(arg0 context.Context, arg1 db.UpdateAmountParams) (db.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAmount", arg0, arg1)
	ret0, _ := ret[0].(db.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAmount indicates an expected call of UpdateAmount.
func (mr *MockStoreMockRecorder) UpdateAmount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAmount", reflect.TypeOf((*MockStore)(nil).UpdateAmount), arg0, arg1)
}

// UpdateBook mocks base method.
func (m *MockStore) UpdateBook(arg0 context.Context, arg1 db.UpdateBookParams) (db.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBook", arg0, arg1)
	ret0, _ := ret[0].(db.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBook indicates an expected call of UpdateBook.
func (mr *MockStoreMockRecorder) UpdateBook(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBook", reflect.TypeOf((*MockStore)(nil).UpdateBook), arg0, arg1)
}

// UpdateGenre mocks base method.
func (m *MockStore) UpdateGenre(arg0 context.Context, arg1 db.UpdateGenreParams) (db.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGenre", arg0, arg1)
	ret0, _ := ret[0].(db.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGenre indicates an expected call of UpdateGenre.
func (mr *MockStoreMockRecorder) UpdateGenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGenre", reflect.TypeOf((*MockStore)(nil).UpdateGenre), arg0, arg1)
}

// UpdateOrder mocks base method.
func (m *MockStore) UpdateOrder(arg0 context.Context, arg1 db.UpdateOrderParams) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockStoreMockRecorder) UpdateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockStore)(nil).UpdateOrder), arg0, arg1)
}

// UpdateResetPassword mocks base method.
func (m *MockStore) UpdateResetPassword(arg0 context.Context, arg1 db.UpdateResetPasswordParams) (db.ResetPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResetPassword", arg0, arg1)
	ret0, _ := ret[0].(db.ResetPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResetPassword indicates an expected call of UpdateResetPassword.
func (mr *MockStoreMockRecorder) UpdateResetPassword(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResetPassword", reflect.TypeOf((*MockStore)(nil).UpdateResetPassword), arg0, arg1)
}

// UpdateSubgenre mocks base method.
func (m *MockStore) UpdateSubgenre(arg0 context.Context, arg1 db.UpdateSubgenreParams) (db.Subgenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubgenre", arg0, arg1)
	ret0, _ := ret[0].(db.Subgenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubgenre indicates an expected call of UpdateSubgenre.
func (mr *MockStoreMockRecorder) UpdateSubgenre(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubgenre", reflect.TypeOf((*MockStore)(nil).UpdateSubgenre), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateVerifyEmail mocks base method.
func (m *MockStore) UpdateVerifyEmail(arg0 context.Context, arg1 db.UpdateVerifyEmailParams) (db.VerifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerifyEmail indicates an expected call of UpdateVerifyEmail.
func (mr *MockStoreMockRecorder) UpdateVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerifyEmail", reflect.TypeOf((*MockStore)(nil).UpdateVerifyEmail), arg0, arg1)
}

// VerifyEmailTx mocks base method.
func (m *MockStore) VerifyEmailTx(arg0 context.Context, arg1 db.VerifyEmailTxParams) (db.VerifyEmailTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailTx", arg0, arg1)
	ret0, _ := ret[0].(db.VerifyEmailTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailTx indicates an expected call of VerifyEmailTx.
func (mr *MockStoreMockRecorder) VerifyEmailTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailTx", reflect.TypeOf((*MockStore)(nil).VerifyEmailTx), arg0, arg1)
}
